version : '3'

services:
    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "server"
        ports:
            - 3001:3001
        working_dir: /app
        command: nodemon nodeapp/app.js 1> error.log
        volumes:
            - .:/app
        links:
            - "database:database"
        tty: true
        restart : always

    react-server:
        build:
            context: .
            dockerfile: Dockerfile:react-client
        container_name: "react"
        ports:
            - 80:80
            - 443:443
            - 3000:3000
        working_dir: /app
        volumes:
            - .:/app
        tty: true
        restart : always

    database:
        container_name: 'db'
        image: "neo4j"
        volumes:
            - ./neo4j/data:/data
        ports:
            - 7687:7687
            - 7474:7474
        environment:
            - NEO4J_AUTH=none
            - NEO4J_apoc_export_file_enabled=true
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_apoc_import_file_use__neo4j__config=true
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*
        restart : always

