version : '3'

services:
    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: 'server'
        ports:
            - 80:80
            - 443:443
            - 3000:3000
        command: nodemon nodeapp/app.js
        volumes :
            - ${PWD}:/app
        restart : on-failure
        tty: true
